# /* **************************************************************************
#  *                                                                          *
#  *     (C) Copyright Paul Mensonides 2002.
#  *     Distributed under the Boost Software License, Version 1.0. (See
#  *     accompanying file LICENSE_1_0.txt or copy at
#  *     http://www.boost.org/LICENSE_1_0.txt)
#  *                                                                          *
#  ************************************************************************** */
#
# /* See http://www.boost.org for most recent version. */
#
# include <packages/boost/include/preprocessor/config/config.hpp>
#
# if UVMSC_BOOST_PP_CONFIG_FLAGS() & UVMSC_BOOST_PP_CONFIG_DMC()
#     include <packages/boost/include/preprocessor/detail/dmc/auto_rec.hpp>
# else
#
# ifndef UVMSC_BOOST_PREPROCESSOR_DETAIL_AUTO_REC_HPP
# define UVMSC_BOOST_PREPROCESSOR_DETAIL_AUTO_REC_HPP
#
# include <packages/boost/include/preprocessor/control/iif.hpp>
#
# /* UVMSC_BOOST_PP_AUTO_REC */
#
# define UVMSC_BOOST_PP_AUTO_REC(pred, n) UVMSC_BOOST_PP_NODE_ENTRY_ ## n(pred)
#
# define UVMSC_BOOST_PP_NODE_ENTRY_256(p) UVMSC_BOOST_PP_NODE_128(p)(p)(p)(p)(p)(p)(p)(p)
# define UVMSC_BOOST_PP_NODE_ENTRY_128(p) UVMSC_BOOST_PP_NODE_64(p)(p)(p)(p)(p)(p)(p)
# define UVMSC_BOOST_PP_NODE_ENTRY_64(p) UVMSC_BOOST_PP_NODE_32(p)(p)(p)(p)(p)(p)
# define UVMSC_BOOST_PP_NODE_ENTRY_32(p) UVMSC_BOOST_PP_NODE_16(p)(p)(p)(p)(p)
# define UVMSC_BOOST_PP_NODE_ENTRY_16(p) UVMSC_BOOST_PP_NODE_8(p)(p)(p)(p)
# define UVMSC_BOOST_PP_NODE_ENTRY_8(p) UVMSC_BOOST_PP_NODE_4(p)(p)(p)
# define UVMSC_BOOST_PP_NODE_ENTRY_4(p) UVMSC_BOOST_PP_NODE_2(p)(p)
# define UVMSC_BOOST_PP_NODE_ENTRY_2(p) UVMSC_BOOST_PP_NODE_1(p)
#
# define UVMSC_BOOST_PP_NODE_128(p) UVMSC_BOOST_PP_IIF(p(128), UVMSC_BOOST_PP_NODE_64, UVMSC_BOOST_PP_NODE_192)
#    define UVMSC_BOOST_PP_NODE_64(p) UVMSC_BOOST_PP_IIF(p(64), UVMSC_BOOST_PP_NODE_32, UVMSC_BOOST_PP_NODE_96)
#        define UVMSC_BOOST_PP_NODE_32(p) UVMSC_BOOST_PP_IIF(p(32), UVMSC_BOOST_PP_NODE_16, UVMSC_BOOST_PP_NODE_48)
#            define UVMSC_BOOST_PP_NODE_16(p) UVMSC_BOOST_PP_IIF(p(16), UVMSC_BOOST_PP_NODE_8, UVMSC_BOOST_PP_NODE_24)
#                define UVMSC_BOOST_PP_NODE_8(p) UVMSC_BOOST_PP_IIF(p(8), UVMSC_BOOST_PP_NODE_4, UVMSC_BOOST_PP_NODE_12)
#                    define UVMSC_BOOST_PP_NODE_4(p) UVMSC_BOOST_PP_IIF(p(4), UVMSC_BOOST_PP_NODE_2, UVMSC_BOOST_PP_NODE_6)
#                        define UVMSC_BOOST_PP_NODE_2(p) UVMSC_BOOST_PP_IIF(p(2), UVMSC_BOOST_PP_NODE_1, UVMSC_BOOST_PP_NODE_3)
#                            define UVMSC_BOOST_PP_NODE_1(p) UVMSC_BOOST_PP_IIF(p(1), 1, 2)
#                            define UVMSC_BOOST_PP_NODE_3(p) UVMSC_BOOST_PP_IIF(p(3), 3, 4)
#                        define UVMSC_BOOST_PP_NODE_6(p) UVMSC_BOOST_PP_IIF(p(6), UVMSC_BOOST_PP_NODE_5, UVMSC_BOOST_PP_NODE_7)
#                            define UVMSC_BOOST_PP_NODE_5(p) UVMSC_BOOST_PP_IIF(p(5), 5, 6)
#                            define UVMSC_BOOST_PP_NODE_7(p) UVMSC_BOOST_PP_IIF(p(7), 7, 8)
#                    define UVMSC_BOOST_PP_NODE_12(p) UVMSC_BOOST_PP_IIF(p(12), UVMSC_BOOST_PP_NODE_10, UVMSC_BOOST_PP_NODE_14)
#                        define UVMSC_BOOST_PP_NODE_10(p) UVMSC_BOOST_PP_IIF(p(10), UVMSC_BOOST_PP_NODE_9, UVMSC_BOOST_PP_NODE_11)
#                            define UVMSC_BOOST_PP_NODE_9(p) UVMSC_BOOST_PP_IIF(p(9), 9, 10)
#                            define UVMSC_BOOST_PP_NODE_11(p) UVMSC_BOOST_PP_IIF(p(11), 11, 12)
#                        define UVMSC_BOOST_PP_NODE_14(p) UVMSC_BOOST_PP_IIF(p(14), UVMSC_BOOST_PP_NODE_13, UVMSC_BOOST_PP_NODE_15)
#                            define UVMSC_BOOST_PP_NODE_13(p) UVMSC_BOOST_PP_IIF(p(13), 13, 14)
#                            define UVMSC_BOOST_PP_NODE_15(p) UVMSC_BOOST_PP_IIF(p(15), 15, 16)
#                define UVMSC_BOOST_PP_NODE_24(p) UVMSC_BOOST_PP_IIF(p(24), UVMSC_BOOST_PP_NODE_20, UVMSC_BOOST_PP_NODE_28)
#                    define UVMSC_BOOST_PP_NODE_20(p) UVMSC_BOOST_PP_IIF(p(20), UVMSC_BOOST_PP_NODE_18, UVMSC_BOOST_PP_NODE_22)
#                        define UVMSC_BOOST_PP_NODE_18(p) UVMSC_BOOST_PP_IIF(p(18), UVMSC_BOOST_PP_NODE_17, UVMSC_BOOST_PP_NODE_19)
#                            define UVMSC_BOOST_PP_NODE_17(p) UVMSC_BOOST_PP_IIF(p(17), 17, 18)
#                            define UVMSC_BOOST_PP_NODE_19(p) UVMSC_BOOST_PP_IIF(p(19), 19, 20)
#                        define UVMSC_BOOST_PP_NODE_22(p) UVMSC_BOOST_PP_IIF(p(22), UVMSC_BOOST_PP_NODE_21, UVMSC_BOOST_PP_NODE_23)
#                            define UVMSC_BOOST_PP_NODE_21(p) UVMSC_BOOST_PP_IIF(p(21), 21, 22)
#                            define UVMSC_BOOST_PP_NODE_23(p) UVMSC_BOOST_PP_IIF(p(23), 23, 24)
#                    define UVMSC_BOOST_PP_NODE_28(p) UVMSC_BOOST_PP_IIF(p(28), UVMSC_BOOST_PP_NODE_26, UVMSC_BOOST_PP_NODE_30)
#                        define UVMSC_BOOST_PP_NODE_26(p) UVMSC_BOOST_PP_IIF(p(26), UVMSC_BOOST_PP_NODE_25, UVMSC_BOOST_PP_NODE_27)
#                            define UVMSC_BOOST_PP_NODE_25(p) UVMSC_BOOST_PP_IIF(p(25), 25, 26)
#                            define UVMSC_BOOST_PP_NODE_27(p) UVMSC_BOOST_PP_IIF(p(27), 27, 28)
#                        define UVMSC_BOOST_PP_NODE_30(p) UVMSC_BOOST_PP_IIF(p(30), UVMSC_BOOST_PP_NODE_29, UVMSC_BOOST_PP_NODE_31)
#                            define UVMSC_BOOST_PP_NODE_29(p) UVMSC_BOOST_PP_IIF(p(29), 29, 30)
#                            define UVMSC_BOOST_PP_NODE_31(p) UVMSC_BOOST_PP_IIF(p(31), 31, 32)
#            define UVMSC_BOOST_PP_NODE_48(p) UVMSC_BOOST_PP_IIF(p(48), UVMSC_BOOST_PP_NODE_40, UVMSC_BOOST_PP_NODE_56)
#                define UVMSC_BOOST_PP_NODE_40(p) UVMSC_BOOST_PP_IIF(p(40), UVMSC_BOOST_PP_NODE_36, UVMSC_BOOST_PP_NODE_44)
#                    define UVMSC_BOOST_PP_NODE_36(p) UVMSC_BOOST_PP_IIF(p(36), UVMSC_BOOST_PP_NODE_34, UVMSC_BOOST_PP_NODE_38)
#                        define UVMSC_BOOST_PP_NODE_34(p) UVMSC_BOOST_PP_IIF(p(34), UVMSC_BOOST_PP_NODE_33, UVMSC_BOOST_PP_NODE_35)
#                            define UVMSC_BOOST_PP_NODE_33(p) UVMSC_BOOST_PP_IIF(p(33), 33, 34)
#                            define UVMSC_BOOST_PP_NODE_35(p) UVMSC_BOOST_PP_IIF(p(35), 35, 36)
#                        define UVMSC_BOOST_PP_NODE_38(p) UVMSC_BOOST_PP_IIF(p(38), UVMSC_BOOST_PP_NODE_37, UVMSC_BOOST_PP_NODE_39)
#                            define UVMSC_BOOST_PP_NODE_37(p) UVMSC_BOOST_PP_IIF(p(37), 37, 38)
#                            define UVMSC_BOOST_PP_NODE_39(p) UVMSC_BOOST_PP_IIF(p(39), 39, 40)
#                    define UVMSC_BOOST_PP_NODE_44(p) UVMSC_BOOST_PP_IIF(p(44), UVMSC_BOOST_PP_NODE_42, UVMSC_BOOST_PP_NODE_46)
#                        define UVMSC_BOOST_PP_NODE_42(p) UVMSC_BOOST_PP_IIF(p(42), UVMSC_BOOST_PP_NODE_41, UVMSC_BOOST_PP_NODE_43)
#                            define UVMSC_BOOST_PP_NODE_41(p) UVMSC_BOOST_PP_IIF(p(41), 41, 42)
#                            define UVMSC_BOOST_PP_NODE_43(p) UVMSC_BOOST_PP_IIF(p(43), 43, 44)
#                        define UVMSC_BOOST_PP_NODE_46(p) UVMSC_BOOST_PP_IIF(p(46), UVMSC_BOOST_PP_NODE_45, UVMSC_BOOST_PP_NODE_47)
#                            define UVMSC_BOOST_PP_NODE_45(p) UVMSC_BOOST_PP_IIF(p(45), 45, 46)
#                            define UVMSC_BOOST_PP_NODE_47(p) UVMSC_BOOST_PP_IIF(p(47), 47, 48)
#                define UVMSC_BOOST_PP_NODE_56(p) UVMSC_BOOST_PP_IIF(p(56), UVMSC_BOOST_PP_NODE_52, UVMSC_BOOST_PP_NODE_60)
#                    define UVMSC_BOOST_PP_NODE_52(p) UVMSC_BOOST_PP_IIF(p(52), UVMSC_BOOST_PP_NODE_50, UVMSC_BOOST_PP_NODE_54)
#                        define UVMSC_BOOST_PP_NODE_50(p) UVMSC_BOOST_PP_IIF(p(50), UVMSC_BOOST_PP_NODE_49, UVMSC_BOOST_PP_NODE_51)
#                            define UVMSC_BOOST_PP_NODE_49(p) UVMSC_BOOST_PP_IIF(p(49), 49, 50)
#                            define UVMSC_BOOST_PP_NODE_51(p) UVMSC_BOOST_PP_IIF(p(51), 51, 52)
#                        define UVMSC_BOOST_PP_NODE_54(p) UVMSC_BOOST_PP_IIF(p(54), UVMSC_BOOST_PP_NODE_53, UVMSC_BOOST_PP_NODE_55)
#                            define UVMSC_BOOST_PP_NODE_53(p) UVMSC_BOOST_PP_IIF(p(53), 53, 54)
#                            define UVMSC_BOOST_PP_NODE_55(p) UVMSC_BOOST_PP_IIF(p(55), 55, 56)
#                    define UVMSC_BOOST_PP_NODE_60(p) UVMSC_BOOST_PP_IIF(p(60), UVMSC_BOOST_PP_NODE_58, UVMSC_BOOST_PP_NODE_62)
#                        define UVMSC_BOOST_PP_NODE_58(p) UVMSC_BOOST_PP_IIF(p(58), UVMSC_BOOST_PP_NODE_57, UVMSC_BOOST_PP_NODE_59)
#                            define UVMSC_BOOST_PP_NODE_57(p) UVMSC_BOOST_PP_IIF(p(57), 57, 58)
#                            define UVMSC_BOOST_PP_NODE_59(p) UVMSC_BOOST_PP_IIF(p(59), 59, 60)
#                        define UVMSC_BOOST_PP_NODE_62(p) UVMSC_BOOST_PP_IIF(p(62), UVMSC_BOOST_PP_NODE_61, UVMSC_BOOST_PP_NODE_63)
#                            define UVMSC_BOOST_PP_NODE_61(p) UVMSC_BOOST_PP_IIF(p(61), 61, 62)
#                            define UVMSC_BOOST_PP_NODE_63(p) UVMSC_BOOST_PP_IIF(p(63), 63, 64)
#        define UVMSC_BOOST_PP_NODE_96(p) UVMSC_BOOST_PP_IIF(p(96), UVMSC_BOOST_PP_NODE_80, UVMSC_BOOST_PP_NODE_112)
#            define UVMSC_BOOST_PP_NODE_80(p) UVMSC_BOOST_PP_IIF(p(80), UVMSC_BOOST_PP_NODE_72, UVMSC_BOOST_PP_NODE_88)
#                define UVMSC_BOOST_PP_NODE_72(p) UVMSC_BOOST_PP_IIF(p(72), UVMSC_BOOST_PP_NODE_68, UVMSC_BOOST_PP_NODE_76)
#                    define UVMSC_BOOST_PP_NODE_68(p) UVMSC_BOOST_PP_IIF(p(68), UVMSC_BOOST_PP_NODE_66, UVMSC_BOOST_PP_NODE_70)
#                        define UVMSC_BOOST_PP_NODE_66(p) UVMSC_BOOST_PP_IIF(p(66), UVMSC_BOOST_PP_NODE_65, UVMSC_BOOST_PP_NODE_67)
#                            define UVMSC_BOOST_PP_NODE_65(p) UVMSC_BOOST_PP_IIF(p(65), 65, 66)
#                            define UVMSC_BOOST_PP_NODE_67(p) UVMSC_BOOST_PP_IIF(p(67), 67, 68)
#                        define UVMSC_BOOST_PP_NODE_70(p) UVMSC_BOOST_PP_IIF(p(70), UVMSC_BOOST_PP_NODE_69, UVMSC_BOOST_PP_NODE_71)
#                            define UVMSC_BOOST_PP_NODE_69(p) UVMSC_BOOST_PP_IIF(p(69), 69, 70)
#                            define UVMSC_BOOST_PP_NODE_71(p) UVMSC_BOOST_PP_IIF(p(71), 71, 72)
#                    define UVMSC_BOOST_PP_NODE_76(p) UVMSC_BOOST_PP_IIF(p(76), UVMSC_BOOST_PP_NODE_74, UVMSC_BOOST_PP_NODE_78)
#                        define UVMSC_BOOST_PP_NODE_74(p) UVMSC_BOOST_PP_IIF(p(74), UVMSC_BOOST_PP_NODE_73, UVMSC_BOOST_PP_NODE_75)
#                            define UVMSC_BOOST_PP_NODE_73(p) UVMSC_BOOST_PP_IIF(p(73), 73, 74)
#                            define UVMSC_BOOST_PP_NODE_75(p) UVMSC_BOOST_PP_IIF(p(75), 75, 76)
#                        define UVMSC_BOOST_PP_NODE_78(p) UVMSC_BOOST_PP_IIF(p(78), UVMSC_BOOST_PP_NODE_77, UVMSC_BOOST_PP_NODE_79)
#                            define UVMSC_BOOST_PP_NODE_77(p) UVMSC_BOOST_PP_IIF(p(77), 77, 78)
#                            define UVMSC_BOOST_PP_NODE_79(p) UVMSC_BOOST_PP_IIF(p(79), 79, 80)
#                define UVMSC_BOOST_PP_NODE_88(p) UVMSC_BOOST_PP_IIF(p(88), UVMSC_BOOST_PP_NODE_84, UVMSC_BOOST_PP_NODE_92)
#                    define UVMSC_BOOST_PP_NODE_84(p) UVMSC_BOOST_PP_IIF(p(84), UVMSC_BOOST_PP_NODE_82, UVMSC_BOOST_PP_NODE_86)
#                        define UVMSC_BOOST_PP_NODE_82(p) UVMSC_BOOST_PP_IIF(p(82), UVMSC_BOOST_PP_NODE_81, UVMSC_BOOST_PP_NODE_83)
#                            define UVMSC_BOOST_PP_NODE_81(p) UVMSC_BOOST_PP_IIF(p(81), 81, 82)
#                            define UVMSC_BOOST_PP_NODE_83(p) UVMSC_BOOST_PP_IIF(p(83), 83, 84)
#                        define UVMSC_BOOST_PP_NODE_86(p) UVMSC_BOOST_PP_IIF(p(86), UVMSC_BOOST_PP_NODE_85, UVMSC_BOOST_PP_NODE_87)
#                            define UVMSC_BOOST_PP_NODE_85(p) UVMSC_BOOST_PP_IIF(p(85), 85, 86)
#                            define UVMSC_BOOST_PP_NODE_87(p) UVMSC_BOOST_PP_IIF(p(87), 87, 88)
#                    define UVMSC_BOOST_PP_NODE_92(p) UVMSC_BOOST_PP_IIF(p(92), UVMSC_BOOST_PP_NODE_90, UVMSC_BOOST_PP_NODE_94)
#                        define UVMSC_BOOST_PP_NODE_90(p) UVMSC_BOOST_PP_IIF(p(90), UVMSC_BOOST_PP_NODE_89, UVMSC_BOOST_PP_NODE_91)
#                            define UVMSC_BOOST_PP_NODE_89(p) UVMSC_BOOST_PP_IIF(p(89), 89, 90)
#                            define UVMSC_BOOST_PP_NODE_91(p) UVMSC_BOOST_PP_IIF(p(91), 91, 92)
#                        define UVMSC_BOOST_PP_NODE_94(p) UVMSC_BOOST_PP_IIF(p(94), UVMSC_BOOST_PP_NODE_93, UVMSC_BOOST_PP_NODE_95)
#                            define UVMSC_BOOST_PP_NODE_93(p) UVMSC_BOOST_PP_IIF(p(93), 93, 94)
#                            define UVMSC_BOOST_PP_NODE_95(p) UVMSC_BOOST_PP_IIF(p(95), 95, 96)
#            define UVMSC_BOOST_PP_NODE_112(p) UVMSC_BOOST_PP_IIF(p(112), UVMSC_BOOST_PP_NODE_104, UVMSC_BOOST_PP_NODE_120)
#                define UVMSC_BOOST_PP_NODE_104(p) UVMSC_BOOST_PP_IIF(p(104), UVMSC_BOOST_PP_NODE_100, UVMSC_BOOST_PP_NODE_108)
#                    define UVMSC_BOOST_PP_NODE_100(p) UVMSC_BOOST_PP_IIF(p(100), UVMSC_BOOST_PP_NODE_98, UVMSC_BOOST_PP_NODE_102)
#                        define UVMSC_BOOST_PP_NODE_98(p) UVMSC_BOOST_PP_IIF(p(98), UVMSC_BOOST_PP_NODE_97, UVMSC_BOOST_PP_NODE_99)
#                            define UVMSC_BOOST_PP_NODE_97(p) UVMSC_BOOST_PP_IIF(p(97), 97, 98)
#                            define UVMSC_BOOST_PP_NODE_99(p) UVMSC_BOOST_PP_IIF(p(99), 99, 100)
#                        define UVMSC_BOOST_PP_NODE_102(p) UVMSC_BOOST_PP_IIF(p(102), UVMSC_BOOST_PP_NODE_101, UVMSC_BOOST_PP_NODE_103)
#                            define UVMSC_BOOST_PP_NODE_101(p) UVMSC_BOOST_PP_IIF(p(101), 101, 102)
#                            define UVMSC_BOOST_PP_NODE_103(p) UVMSC_BOOST_PP_IIF(p(103), 103, 104)
#                    define UVMSC_BOOST_PP_NODE_108(p) UVMSC_BOOST_PP_IIF(p(108), UVMSC_BOOST_PP_NODE_106, UVMSC_BOOST_PP_NODE_110)
#                        define UVMSC_BOOST_PP_NODE_106(p) UVMSC_BOOST_PP_IIF(p(106), UVMSC_BOOST_PP_NODE_105, UVMSC_BOOST_PP_NODE_107)
#                            define UVMSC_BOOST_PP_NODE_105(p) UVMSC_BOOST_PP_IIF(p(105), 105, 106)
#                            define UVMSC_BOOST_PP_NODE_107(p) UVMSC_BOOST_PP_IIF(p(107), 107, 108)
#                        define UVMSC_BOOST_PP_NODE_110(p) UVMSC_BOOST_PP_IIF(p(110), UVMSC_BOOST_PP_NODE_109, UVMSC_BOOST_PP_NODE_111)
#                            define UVMSC_BOOST_PP_NODE_109(p) UVMSC_BOOST_PP_IIF(p(109), 109, 110)
#                            define UVMSC_BOOST_PP_NODE_111(p) UVMSC_BOOST_PP_IIF(p(111), 111, 112)
#                define UVMSC_BOOST_PP_NODE_120(p) UVMSC_BOOST_PP_IIF(p(120), UVMSC_BOOST_PP_NODE_116, UVMSC_BOOST_PP_NODE_124)
#                    define UVMSC_BOOST_PP_NODE_116(p) UVMSC_BOOST_PP_IIF(p(116), UVMSC_BOOST_PP_NODE_114, UVMSC_BOOST_PP_NODE_118)
#                        define UVMSC_BOOST_PP_NODE_114(p) UVMSC_BOOST_PP_IIF(p(114), UVMSC_BOOST_PP_NODE_113, UVMSC_BOOST_PP_NODE_115)
#                            define UVMSC_BOOST_PP_NODE_113(p) UVMSC_BOOST_PP_IIF(p(113), 113, 114)
#                            define UVMSC_BOOST_PP_NODE_115(p) UVMSC_BOOST_PP_IIF(p(115), 115, 116)
#                        define UVMSC_BOOST_PP_NODE_118(p) UVMSC_BOOST_PP_IIF(p(118), UVMSC_BOOST_PP_NODE_117, UVMSC_BOOST_PP_NODE_119)
#                            define UVMSC_BOOST_PP_NODE_117(p) UVMSC_BOOST_PP_IIF(p(117), 117, 118)
#                            define UVMSC_BOOST_PP_NODE_119(p) UVMSC_BOOST_PP_IIF(p(119), 119, 120)
#                    define UVMSC_BOOST_PP_NODE_124(p) UVMSC_BOOST_PP_IIF(p(124), UVMSC_BOOST_PP_NODE_122, UVMSC_BOOST_PP_NODE_126)
#                        define UVMSC_BOOST_PP_NODE_122(p) UVMSC_BOOST_PP_IIF(p(122), UVMSC_BOOST_PP_NODE_121, UVMSC_BOOST_PP_NODE_123)
#                            define UVMSC_BOOST_PP_NODE_121(p) UVMSC_BOOST_PP_IIF(p(121), 121, 122)
#                            define UVMSC_BOOST_PP_NODE_123(p) UVMSC_BOOST_PP_IIF(p(123), 123, 124)
#                        define UVMSC_BOOST_PP_NODE_126(p) UVMSC_BOOST_PP_IIF(p(126), UVMSC_BOOST_PP_NODE_125, UVMSC_BOOST_PP_NODE_127)
#                            define UVMSC_BOOST_PP_NODE_125(p) UVMSC_BOOST_PP_IIF(p(125), 125, 126)
#                            define UVMSC_BOOST_PP_NODE_127(p) UVMSC_BOOST_PP_IIF(p(127), 127, 128)
#    define UVMSC_BOOST_PP_NODE_192(p) UVMSC_BOOST_PP_IIF(p(192), UVMSC_BOOST_PP_NODE_160, UVMSC_BOOST_PP_NODE_224)
#        define UVMSC_BOOST_PP_NODE_160(p) UVMSC_BOOST_PP_IIF(p(160), UVMSC_BOOST_PP_NODE_144, UVMSC_BOOST_PP_NODE_176)
#            define UVMSC_BOOST_PP_NODE_144(p) UVMSC_BOOST_PP_IIF(p(144), UVMSC_BOOST_PP_NODE_136, UVMSC_BOOST_PP_NODE_152)
#                define UVMSC_BOOST_PP_NODE_136(p) UVMSC_BOOST_PP_IIF(p(136), UVMSC_BOOST_PP_NODE_132, UVMSC_BOOST_PP_NODE_140)
#                    define UVMSC_BOOST_PP_NODE_132(p) UVMSC_BOOST_PP_IIF(p(132), UVMSC_BOOST_PP_NODE_130, UVMSC_BOOST_PP_NODE_134)
#                        define UVMSC_BOOST_PP_NODE_130(p) UVMSC_BOOST_PP_IIF(p(130), UVMSC_BOOST_PP_NODE_129, UVMSC_BOOST_PP_NODE_131)
#                            define UVMSC_BOOST_PP_NODE_129(p) UVMSC_BOOST_PP_IIF(p(129), 129, 130)
#                            define UVMSC_BOOST_PP_NODE_131(p) UVMSC_BOOST_PP_IIF(p(131), 131, 132)
#                        define UVMSC_BOOST_PP_NODE_134(p) UVMSC_BOOST_PP_IIF(p(134), UVMSC_BOOST_PP_NODE_133, UVMSC_BOOST_PP_NODE_135)
#                            define UVMSC_BOOST_PP_NODE_133(p) UVMSC_BOOST_PP_IIF(p(133), 133, 134)
#                            define UVMSC_BOOST_PP_NODE_135(p) UVMSC_BOOST_PP_IIF(p(135), 135, 136)
#                    define UVMSC_BOOST_PP_NODE_140(p) UVMSC_BOOST_PP_IIF(p(140), UVMSC_BOOST_PP_NODE_138, UVMSC_BOOST_PP_NODE_142)
#                        define UVMSC_BOOST_PP_NODE_138(p) UVMSC_BOOST_PP_IIF(p(138), UVMSC_BOOST_PP_NODE_137, UVMSC_BOOST_PP_NODE_139)
#                            define UVMSC_BOOST_PP_NODE_137(p) UVMSC_BOOST_PP_IIF(p(137), 137, 138)
#                            define UVMSC_BOOST_PP_NODE_139(p) UVMSC_BOOST_PP_IIF(p(139), 139, 140)
#                        define UVMSC_BOOST_PP_NODE_142(p) UVMSC_BOOST_PP_IIF(p(142), UVMSC_BOOST_PP_NODE_141, UVMSC_BOOST_PP_NODE_143)
#                            define UVMSC_BOOST_PP_NODE_141(p) UVMSC_BOOST_PP_IIF(p(141), 141, 142)
#                            define UVMSC_BOOST_PP_NODE_143(p) UVMSC_BOOST_PP_IIF(p(143), 143, 144)
#                define UVMSC_BOOST_PP_NODE_152(p) UVMSC_BOOST_PP_IIF(p(152), UVMSC_BOOST_PP_NODE_148, UVMSC_BOOST_PP_NODE_156)
#                    define UVMSC_BOOST_PP_NODE_148(p) UVMSC_BOOST_PP_IIF(p(148), UVMSC_BOOST_PP_NODE_146, UVMSC_BOOST_PP_NODE_150)
#                        define UVMSC_BOOST_PP_NODE_146(p) UVMSC_BOOST_PP_IIF(p(146), UVMSC_BOOST_PP_NODE_145, UVMSC_BOOST_PP_NODE_147)
#                            define UVMSC_BOOST_PP_NODE_145(p) UVMSC_BOOST_PP_IIF(p(145), 145, 146)
#                            define UVMSC_BOOST_PP_NODE_147(p) UVMSC_BOOST_PP_IIF(p(147), 147, 148)
#                        define UVMSC_BOOST_PP_NODE_150(p) UVMSC_BOOST_PP_IIF(p(150), UVMSC_BOOST_PP_NODE_149, UVMSC_BOOST_PP_NODE_151)
#                            define UVMSC_BOOST_PP_NODE_149(p) UVMSC_BOOST_PP_IIF(p(149), 149, 150)
#                            define UVMSC_BOOST_PP_NODE_151(p) UVMSC_BOOST_PP_IIF(p(151), 151, 152)
#                    define UVMSC_BOOST_PP_NODE_156(p) UVMSC_BOOST_PP_IIF(p(156), UVMSC_BOOST_PP_NODE_154, UVMSC_BOOST_PP_NODE_158)
#                        define UVMSC_BOOST_PP_NODE_154(p) UVMSC_BOOST_PP_IIF(p(154), UVMSC_BOOST_PP_NODE_153, UVMSC_BOOST_PP_NODE_155)
#                            define UVMSC_BOOST_PP_NODE_153(p) UVMSC_BOOST_PP_IIF(p(153), 153, 154)
#                            define UVMSC_BOOST_PP_NODE_155(p) UVMSC_BOOST_PP_IIF(p(155), 155, 156)
#                        define UVMSC_BOOST_PP_NODE_158(p) UVMSC_BOOST_PP_IIF(p(158), UVMSC_BOOST_PP_NODE_157, UVMSC_BOOST_PP_NODE_159)
#                            define UVMSC_BOOST_PP_NODE_157(p) UVMSC_BOOST_PP_IIF(p(157), 157, 158)
#                            define UVMSC_BOOST_PP_NODE_159(p) UVMSC_BOOST_PP_IIF(p(159), 159, 160)
#            define UVMSC_BOOST_PP_NODE_176(p) UVMSC_BOOST_PP_IIF(p(176), UVMSC_BOOST_PP_NODE_168, UVMSC_BOOST_PP_NODE_184)
#                define UVMSC_BOOST_PP_NODE_168(p) UVMSC_BOOST_PP_IIF(p(168), UVMSC_BOOST_PP_NODE_164, UVMSC_BOOST_PP_NODE_172)
#                    define UVMSC_BOOST_PP_NODE_164(p) UVMSC_BOOST_PP_IIF(p(164), UVMSC_BOOST_PP_NODE_162, UVMSC_BOOST_PP_NODE_166)
#                        define UVMSC_BOOST_PP_NODE_162(p) UVMSC_BOOST_PP_IIF(p(162), UVMSC_BOOST_PP_NODE_161, UVMSC_BOOST_PP_NODE_163)
#                            define UVMSC_BOOST_PP_NODE_161(p) UVMSC_BOOST_PP_IIF(p(161), 161, 162)
#                            define UVMSC_BOOST_PP_NODE_163(p) UVMSC_BOOST_PP_IIF(p(163), 163, 164)
#                        define UVMSC_BOOST_PP_NODE_166(p) UVMSC_BOOST_PP_IIF(p(166), UVMSC_BOOST_PP_NODE_165, UVMSC_BOOST_PP_NODE_167)
#                            define UVMSC_BOOST_PP_NODE_165(p) UVMSC_BOOST_PP_IIF(p(165), 165, 166)
#                            define UVMSC_BOOST_PP_NODE_167(p) UVMSC_BOOST_PP_IIF(p(167), 167, 168)
#                    define UVMSC_BOOST_PP_NODE_172(p) UVMSC_BOOST_PP_IIF(p(172), UVMSC_BOOST_PP_NODE_170, UVMSC_BOOST_PP_NODE_174)
#                        define UVMSC_BOOST_PP_NODE_170(p) UVMSC_BOOST_PP_IIF(p(170), UVMSC_BOOST_PP_NODE_169, UVMSC_BOOST_PP_NODE_171)
#                            define UVMSC_BOOST_PP_NODE_169(p) UVMSC_BOOST_PP_IIF(p(169), 169, 170)
#                            define UVMSC_BOOST_PP_NODE_171(p) UVMSC_BOOST_PP_IIF(p(171), 171, 172)
#                        define UVMSC_BOOST_PP_NODE_174(p) UVMSC_BOOST_PP_IIF(p(174), UVMSC_BOOST_PP_NODE_173, UVMSC_BOOST_PP_NODE_175)
#                            define UVMSC_BOOST_PP_NODE_173(p) UVMSC_BOOST_PP_IIF(p(173), 173, 174)
#                            define UVMSC_BOOST_PP_NODE_175(p) UVMSC_BOOST_PP_IIF(p(175), 175, 176)
#                define UVMSC_BOOST_PP_NODE_184(p) UVMSC_BOOST_PP_IIF(p(184), UVMSC_BOOST_PP_NODE_180, UVMSC_BOOST_PP_NODE_188)
#                    define UVMSC_BOOST_PP_NODE_180(p) UVMSC_BOOST_PP_IIF(p(180), UVMSC_BOOST_PP_NODE_178, UVMSC_BOOST_PP_NODE_182)
#                        define UVMSC_BOOST_PP_NODE_178(p) UVMSC_BOOST_PP_IIF(p(178), UVMSC_BOOST_PP_NODE_177, UVMSC_BOOST_PP_NODE_179)
#                            define UVMSC_BOOST_PP_NODE_177(p) UVMSC_BOOST_PP_IIF(p(177), 177, 178)
#                            define UVMSC_BOOST_PP_NODE_179(p) UVMSC_BOOST_PP_IIF(p(179), 179, 180)
#                        define UVMSC_BOOST_PP_NODE_182(p) UVMSC_BOOST_PP_IIF(p(182), UVMSC_BOOST_PP_NODE_181, UVMSC_BOOST_PP_NODE_183)
#                            define UVMSC_BOOST_PP_NODE_181(p) UVMSC_BOOST_PP_IIF(p(181), 181, 182)
#                            define UVMSC_BOOST_PP_NODE_183(p) UVMSC_BOOST_PP_IIF(p(183), 183, 184)
#                    define UVMSC_BOOST_PP_NODE_188(p) UVMSC_BOOST_PP_IIF(p(188), UVMSC_BOOST_PP_NODE_186, UVMSC_BOOST_PP_NODE_190)
#                        define UVMSC_BOOST_PP_NODE_186(p) UVMSC_BOOST_PP_IIF(p(186), UVMSC_BOOST_PP_NODE_185, UVMSC_BOOST_PP_NODE_187)
#                            define UVMSC_BOOST_PP_NODE_185(p) UVMSC_BOOST_PP_IIF(p(185), 185, 186)
#                            define UVMSC_BOOST_PP_NODE_187(p) UVMSC_BOOST_PP_IIF(p(187), 187, 188)
#                        define UVMSC_BOOST_PP_NODE_190(p) UVMSC_BOOST_PP_IIF(p(190), UVMSC_BOOST_PP_NODE_189, UVMSC_BOOST_PP_NODE_191)
#                            define UVMSC_BOOST_PP_NODE_189(p) UVMSC_BOOST_PP_IIF(p(189), 189, 190)
#                            define UVMSC_BOOST_PP_NODE_191(p) UVMSC_BOOST_PP_IIF(p(191), 191, 192)
#        define UVMSC_BOOST_PP_NODE_224(p) UVMSC_BOOST_PP_IIF(p(224), UVMSC_BOOST_PP_NODE_208, UVMSC_BOOST_PP_NODE_240)
#            define UVMSC_BOOST_PP_NODE_208(p) UVMSC_BOOST_PP_IIF(p(208), UVMSC_BOOST_PP_NODE_200, UVMSC_BOOST_PP_NODE_216)
#                define UVMSC_BOOST_PP_NODE_200(p) UVMSC_BOOST_PP_IIF(p(200), UVMSC_BOOST_PP_NODE_196, UVMSC_BOOST_PP_NODE_204)
#                    define UVMSC_BOOST_PP_NODE_196(p) UVMSC_BOOST_PP_IIF(p(196), UVMSC_BOOST_PP_NODE_194, UVMSC_BOOST_PP_NODE_198)
#                        define UVMSC_BOOST_PP_NODE_194(p) UVMSC_BOOST_PP_IIF(p(194), UVMSC_BOOST_PP_NODE_193, UVMSC_BOOST_PP_NODE_195)
#                            define UVMSC_BOOST_PP_NODE_193(p) UVMSC_BOOST_PP_IIF(p(193), 193, 194)
#                            define UVMSC_BOOST_PP_NODE_195(p) UVMSC_BOOST_PP_IIF(p(195), 195, 196)
#                        define UVMSC_BOOST_PP_NODE_198(p) UVMSC_BOOST_PP_IIF(p(198), UVMSC_BOOST_PP_NODE_197, UVMSC_BOOST_PP_NODE_199)
#                            define UVMSC_BOOST_PP_NODE_197(p) UVMSC_BOOST_PP_IIF(p(197), 197, 198)
#                            define UVMSC_BOOST_PP_NODE_199(p) UVMSC_BOOST_PP_IIF(p(199), 199, 200)
#                    define UVMSC_BOOST_PP_NODE_204(p) UVMSC_BOOST_PP_IIF(p(204), UVMSC_BOOST_PP_NODE_202, UVMSC_BOOST_PP_NODE_206)
#                        define UVMSC_BOOST_PP_NODE_202(p) UVMSC_BOOST_PP_IIF(p(202), UVMSC_BOOST_PP_NODE_201, UVMSC_BOOST_PP_NODE_203)
#                            define UVMSC_BOOST_PP_NODE_201(p) UVMSC_BOOST_PP_IIF(p(201), 201, 202)
#                            define UVMSC_BOOST_PP_NODE_203(p) UVMSC_BOOST_PP_IIF(p(203), 203, 204)
#                        define UVMSC_BOOST_PP_NODE_206(p) UVMSC_BOOST_PP_IIF(p(206), UVMSC_BOOST_PP_NODE_205, UVMSC_BOOST_PP_NODE_207)
#                            define UVMSC_BOOST_PP_NODE_205(p) UVMSC_BOOST_PP_IIF(p(205), 205, 206)
#                            define UVMSC_BOOST_PP_NODE_207(p) UVMSC_BOOST_PP_IIF(p(207), 207, 208)
#                define UVMSC_BOOST_PP_NODE_216(p) UVMSC_BOOST_PP_IIF(p(216), UVMSC_BOOST_PP_NODE_212, UVMSC_BOOST_PP_NODE_220)
#                    define UVMSC_BOOST_PP_NODE_212(p) UVMSC_BOOST_PP_IIF(p(212), UVMSC_BOOST_PP_NODE_210, UVMSC_BOOST_PP_NODE_214)
#                        define UVMSC_BOOST_PP_NODE_210(p) UVMSC_BOOST_PP_IIF(p(210), UVMSC_BOOST_PP_NODE_209, UVMSC_BOOST_PP_NODE_211)
#                            define UVMSC_BOOST_PP_NODE_209(p) UVMSC_BOOST_PP_IIF(p(209), 209, 210)
#                            define UVMSC_BOOST_PP_NODE_211(p) UVMSC_BOOST_PP_IIF(p(211), 211, 212)
#                        define UVMSC_BOOST_PP_NODE_214(p) UVMSC_BOOST_PP_IIF(p(214), UVMSC_BOOST_PP_NODE_213, UVMSC_BOOST_PP_NODE_215)
#                            define UVMSC_BOOST_PP_NODE_213(p) UVMSC_BOOST_PP_IIF(p(213), 213, 214)
#                            define UVMSC_BOOST_PP_NODE_215(p) UVMSC_BOOST_PP_IIF(p(215), 215, 216)
#                    define UVMSC_BOOST_PP_NODE_220(p) UVMSC_BOOST_PP_IIF(p(220), UVMSC_BOOST_PP_NODE_218, UVMSC_BOOST_PP_NODE_222)
#                        define UVMSC_BOOST_PP_NODE_218(p) UVMSC_BOOST_PP_IIF(p(218), UVMSC_BOOST_PP_NODE_217, UVMSC_BOOST_PP_NODE_219)
#                            define UVMSC_BOOST_PP_NODE_217(p) UVMSC_BOOST_PP_IIF(p(217), 217, 218)
#                            define UVMSC_BOOST_PP_NODE_219(p) UVMSC_BOOST_PP_IIF(p(219), 219, 220)
#                        define UVMSC_BOOST_PP_NODE_222(p) UVMSC_BOOST_PP_IIF(p(222), UVMSC_BOOST_PP_NODE_221, UVMSC_BOOST_PP_NODE_223)
#                            define UVMSC_BOOST_PP_NODE_221(p) UVMSC_BOOST_PP_IIF(p(221), 221, 222)
#                            define UVMSC_BOOST_PP_NODE_223(p) UVMSC_BOOST_PP_IIF(p(223), 223, 224)
#            define UVMSC_BOOST_PP_NODE_240(p) UVMSC_BOOST_PP_IIF(p(240), UVMSC_BOOST_PP_NODE_232, UVMSC_BOOST_PP_NODE_248)
#                define UVMSC_BOOST_PP_NODE_232(p) UVMSC_BOOST_PP_IIF(p(232), UVMSC_BOOST_PP_NODE_228, UVMSC_BOOST_PP_NODE_236)
#                    define UVMSC_BOOST_PP_NODE_228(p) UVMSC_BOOST_PP_IIF(p(228), UVMSC_BOOST_PP_NODE_226, UVMSC_BOOST_PP_NODE_230)
#                        define UVMSC_BOOST_PP_NODE_226(p) UVMSC_BOOST_PP_IIF(p(226), UVMSC_BOOST_PP_NODE_225, UVMSC_BOOST_PP_NODE_227)
#                            define UVMSC_BOOST_PP_NODE_225(p) UVMSC_BOOST_PP_IIF(p(225), 225, 226)
#                            define UVMSC_BOOST_PP_NODE_227(p) UVMSC_BOOST_PP_IIF(p(227), 227, 228)
#                        define UVMSC_BOOST_PP_NODE_230(p) UVMSC_BOOST_PP_IIF(p(230), UVMSC_BOOST_PP_NODE_229, UVMSC_BOOST_PP_NODE_231)
#                            define UVMSC_BOOST_PP_NODE_229(p) UVMSC_BOOST_PP_IIF(p(229), 229, 230)
#                            define UVMSC_BOOST_PP_NODE_231(p) UVMSC_BOOST_PP_IIF(p(231), 231, 232)
#                    define UVMSC_BOOST_PP_NODE_236(p) UVMSC_BOOST_PP_IIF(p(236), UVMSC_BOOST_PP_NODE_234, UVMSC_BOOST_PP_NODE_238)
#                        define UVMSC_BOOST_PP_NODE_234(p) UVMSC_BOOST_PP_IIF(p(234), UVMSC_BOOST_PP_NODE_233, UVMSC_BOOST_PP_NODE_235)
#                            define UVMSC_BOOST_PP_NODE_233(p) UVMSC_BOOST_PP_IIF(p(233), 233, 234)
#                            define UVMSC_BOOST_PP_NODE_235(p) UVMSC_BOOST_PP_IIF(p(235), 235, 236)
#                        define UVMSC_BOOST_PP_NODE_238(p) UVMSC_BOOST_PP_IIF(p(238), UVMSC_BOOST_PP_NODE_237, UVMSC_BOOST_PP_NODE_239)
#                            define UVMSC_BOOST_PP_NODE_237(p) UVMSC_BOOST_PP_IIF(p(237), 237, 238)
#                            define UVMSC_BOOST_PP_NODE_239(p) UVMSC_BOOST_PP_IIF(p(239), 239, 240)
#                define UVMSC_BOOST_PP_NODE_248(p) UVMSC_BOOST_PP_IIF(p(248), UVMSC_BOOST_PP_NODE_244, UVMSC_BOOST_PP_NODE_252)
#                    define UVMSC_BOOST_PP_NODE_244(p) UVMSC_BOOST_PP_IIF(p(244), UVMSC_BOOST_PP_NODE_242, UVMSC_BOOST_PP_NODE_246)
#                        define UVMSC_BOOST_PP_NODE_242(p) UVMSC_BOOST_PP_IIF(p(242), UVMSC_BOOST_PP_NODE_241, UVMSC_BOOST_PP_NODE_243)
#                            define UVMSC_BOOST_PP_NODE_241(p) UVMSC_BOOST_PP_IIF(p(241), 241, 242)
#                            define UVMSC_BOOST_PP_NODE_243(p) UVMSC_BOOST_PP_IIF(p(243), 243, 244)
#                        define UVMSC_BOOST_PP_NODE_246(p) UVMSC_BOOST_PP_IIF(p(246), UVMSC_BOOST_PP_NODE_245, UVMSC_BOOST_PP_NODE_247)
#                            define UVMSC_BOOST_PP_NODE_245(p) UVMSC_BOOST_PP_IIF(p(245), 245, 246)
#                            define UVMSC_BOOST_PP_NODE_247(p) UVMSC_BOOST_PP_IIF(p(247), 247, 248)
#                    define UVMSC_BOOST_PP_NODE_252(p) UVMSC_BOOST_PP_IIF(p(252), UVMSC_BOOST_PP_NODE_250, UVMSC_BOOST_PP_NODE_254)
#                        define UVMSC_BOOST_PP_NODE_250(p) UVMSC_BOOST_PP_IIF(p(250), UVMSC_BOOST_PP_NODE_249, UVMSC_BOOST_PP_NODE_251)
#                            define UVMSC_BOOST_PP_NODE_249(p) UVMSC_BOOST_PP_IIF(p(249), 249, 250)
#                            define UVMSC_BOOST_PP_NODE_251(p) UVMSC_BOOST_PP_IIF(p(251), 251, 252)
#                        define UVMSC_BOOST_PP_NODE_254(p) UVMSC_BOOST_PP_IIF(p(254), UVMSC_BOOST_PP_NODE_253, UVMSC_BOOST_PP_NODE_255)
#                            define UVMSC_BOOST_PP_NODE_253(p) UVMSC_BOOST_PP_IIF(p(253), 253, 254)
#                            define UVMSC_BOOST_PP_NODE_255(p) UVMSC_BOOST_PP_IIF(p(255), 255, 256)
#
# endif
# endif
